# Generated by Django 5.0.4 on 2024-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting.', max_length=254, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('parameter', models.CharField(blank=True, default='', max_length=254, verbose_name='Parameter')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'WorkSingle',
                'verbose_name_plural': 'WorkSingles',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('name',), 'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
    ]
